branch-defaults:
  master:
    environment: demo-06-23
    group_suffix: null
global:
  application_name: ascott-inv-mgmt
  branch: null
  default_ec2_keyname: capstone
  default_platform: python2.7
  default_region: ap-southeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
